version: "2"
services:
  app:
    build: ./app
    ports:
      - "5000:5000"
    networks:
      service_net:
        ipv4_address: 172.33.0.100
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    networks:
      service_net:
        ipv4_address: 172.33.0.101
networks:
  service_net:
    ipam:
      driver: default
      config:
        - subnet: 172.33.0.0/16